# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKjrhaA6NtBDD0q2mub_ZTJ68wnsJNFF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df1=pd.read_csv('salary-dataset.csv')

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to the 'company_size' column
df1['company_size_encoded'] = le.fit_transform(df1['company_size'])

print('DataFrame df1 with encoded \'company_size\' column:')
display(df1[['company_size', 'company_size_encoded']].head())

df1

# Select only numerical columns for correlation analysis
numerical_df1 = df1.select_dtypes(include=[np.number])

# Drop 'Unnamed: 0' as it's likely just an index and 'salary' as 'salary_in_usd' is available
numerical_df1 = numerical_df1.drop(columns=['Unnamed: 0', 'salary'], errors='ignore')

# Calculate the correlation matrix
corr_matrix = numerical_df1.corr()

# Plot the correlation heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numerical Features in df1')
plt.show()

"""### Preparing Data for Model Training on `df1`

Now, we'll prepare `df1` for model training. The target variable will be `salary_in_usd`, and the features will include `work_year`, `remote_ratio`, and the encoded `company_size_encoded`.
"""

from sklearn.model_selection import train_test_split

# Define features (X_df1) and target (y_df1) for df1
X_df1 = df1[['work_year', 'remote_ratio', 'company_size_encoded']]
y_df1 = df1['salary_in_usd']

# Split data into training and testing sets
X_train_df1, X_test_df1, y_train_df1, y_test_df1 = train_test_split(X_df1, y_df1, test_size=0.25, random_state=42)

print(f'X_train_df1 shape: {X_train_df1.shape}')
print(f'y_train_df1 shape: {y_train_df1.shape}')
print(f'X_test_df1 shape: {X_test_df1.shape}')
print(f'y_test_df1 shape: {y_test_df1.shape}')

"""### Ensemble Learning with K-Fold Cross-Validation for `df1`

We will now evaluate the same set of regression models (Linear Regression, Decision Tree, Random Forest, Gradient Boosting, SVR, and K-Neighbors Regressor) on `df1` using K-Fold Cross-Validation, assessing their performance with Root Mean Squared Error (RMSE).
"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error
import numpy as np

# Initialize models
models_df1 = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'SVR': SVR(),
    'K-Neighbors': KNeighborsRegressor()
}

# Set up K-Fold Cross-Validation
kf_df1 = KFold(n_splits=5, shuffle=True, random_state=42)

results_df1 = {}

print('Performing K-Fold Cross-Validation for each model on df1:')

for name, model in models_df1.items():
    # Use negative mean squared error as scoring for cross_val_score
    # We'll take the square root to get RMSE
    scores_df1 = cross_val_score(model, X_train_df1, y_train_df1, cv=kf_df1, scoring='neg_mean_squared_error', n_jobs=-1)
    rmse_scores_df1 = np.sqrt(-scores_df1)

    results_df1[name] = {
        'RMSE_mean': rmse_scores_df1.mean(),
        'RMSE_std': rmse_scores_df1.std()
    }
    print(f'{name}: Mean RMSE = {results_df1[name]['RMSE_mean']:.2f}, Std RMSE = {results_df1[name]['RMSE_std']:.2f}')

# Display results in a DataFrame for easier comparison
results_df1_df = pd.DataFrame(results_df1).T
results_df1_df = results_df1_df.sort_values(by='RMSE_mean')

print('\nComparison of Model Performance on df1 (RMSE):')
display(results_df1_df)

"""### Visualizing Model Performance on `df1`

Let's visualize the Mean RMSE of each model to easily compare their performance on the `df1` dataset.
"""

plt.figure(figsize=(12, 7))
sns.barplot(x=results_df1_df.index, y='RMSE_mean', data=results_df1_df, hue=results_df1_df.index, palette='viridis', legend=False)
plt.title('Mean RMSE of Regression Models on df1')
plt.xlabel('Model')
plt.ylabel('Mean RMSE')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import pickle as pkl

# Identify the best performing model based on mean RMSE
best_model_name_df1 = results_df1_df.index[0]
best_model_df1 = models_df1[best_model_name_df1]

# Train the best model on the entire training data
best_model_df1.fit(X_train_df1, y_train_df1)

# Define a filename for the pickle file
filename = f'{best_model_name_df1.replace(' ', '_').lower()}_df1_model.pkl'

# Save the trained model to a pickle file
with open(filename, 'wb') as file:
    pkl.dump(best_model_df1, file)

print(f'Successfully saved the best model ({best_model_name_df1}) to {filename}')

"""### Streamlit App for Model Deployment

To deploy your model, you'll create a Python file (e.g., `app.py`) with the following content. Make sure this file is in the same directory as your `gradient_boosting_df1_model.pkl` file, or adjust the path accordingly.
"""

import streamlit as st
import pandas as pd
import pickle as pkl

# Load the trained model
@st.cache_resource # Cache the model loading to prevent re-loading on each rerun
def load_model():
    with open('gradient_boosting_df1_model.pkl', 'rb') as file:
        model = pkl.load(file)
    return model

model = load_model()

st.title('Salary Prediction App')
st.write('Enter the details to predict the salary in USD.')

# Input fields for the features
work_year = st.slider('Work Year', min_value=2020, max_value=2025, value=2022)
remote_ratio = st.slider('Remote Ratio (0 = On-site, 50 = Hybrid, 100 = Remote)', min_value=0, max_value=100, step=50, value=100)

company_size_map = {'Small': 2, 'Medium': 1, 'Large': 0}
company_size_display = st.selectbox('Company Size', options=list(company_size_map.keys()))
company_size_encoded = company_size_map[company_size_display]

# Create a DataFrame for prediction
input_data = pd.DataFrame({
    'work_year': [work_year],
    'remote_ratio': [remote_ratio],
    'company_size_encoded': [company_size_encoded]
})

if st.button('Predict Salary'):
    prediction = model.predict(input_data)[0]
    st.success(f'Predicted Salary: ${prediction:,.2f} USD')

"""To run this application:

1.  Save the code above into a file named `app.py` in the same directory as your `gradient_boosting_df1_model.pkl`.
2.  Open your terminal or command prompt.
3.  Navigate to that directory.
4.  Run the command: `streamlit run app.py`

This will open the Streamlit app in your web browser.
"""